apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ads-app
    repoURL: https://github.com/zahidiqbalnbs/gitchartsrepo
    targetRevision: 0.1.0
