apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ads-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ads-chart
    repoURL: https://zahidiqbalnbs.github.io/gitchartsrepo
    targetRevision: 0.1.0
