apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ads-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ads-chart
    repoURL: https://zahidiqbalnbs.github.io/gitchartsrepo
    targetRevision: 0.1.1
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
